# Tell CloudCannon where your Hugo folders live
paths:
  uploads: static/images
  data: data
  collections: content

# Configure the sidebar to show your Markdown files
collections_config:
  content:
    path: content
    output: true
    name: Pages

# Turn on the visual and content editing panels
_select_editor:
  visual: true
  content: true
